USE sales;

SELECT * from sales;


-- 1️⃣ Show all orders placed from Mumbai.
SELECT order_id,city,category from sales 
where city='Mumbai';


-- 2️⃣ Display all orders where price is greater than 50,000.
SELECT * FROM sales 
where price>50000;


-- 3️⃣ Show the first 10 orders sorted by order_date (latest first).
SELECT order_id, order_date 
FROM sales
ORDER BY order_date DESC
LIMIT 10;


-- 4️⃣ Count how many total orders are in the dataset.
SELECT COUNT(*) AS total_orders
FROM sales;

-- 5️⃣ Find how many unique cities are present.
select count(distinct(city)) from sales;
-- 6️⃣ Show all orders where category is Electronics and quantity > 2.
select * from sales
where category='Electronics' and quantity>2;

------------------------------------------------------------------------------------------------
-- 7️⃣ Find total revenue (sum of total_amount).
SELECT sum(total_amount) as total_revenue FROM SALES;


8️⃣ Find total revenue generated by each category.
SELECT category,sum(total_amount) from sales
GROUP BY category ; 

-- 9️⃣ Find total quantity sold per city.
SELECT city,sum(quantity) as sold_per_city from sales
GROUP BY city;

-- 🔟 Which city generated the highest revenue?
SELECT city,sum(total_amount) as revenue from sales
GROUP BY city;

-- 1️⃣1️⃣ Find the average order value per category.
SELECT category, AVG(total_amount) AS avg_order_value
FROM sales
GROUP BY category;



-- 1️⃣2️⃣ Find top 5 customers (customer_id) based on total spending.
SELECT * FROM SALES;
SELECT customer_id,sum(total_amount) as spending  from sales
GROUP BY customer_id 
order by spending desc limit 5;
---------------------------------------------------------------------------------------------------


-- Find customers who placed more than 5 orders.
SELECT customer_id, COUNT(order_id) AS total_orders
FROM sales
GROUP BY customer_id
HAVING COUNT(order_id) > 5;

select * from sales;

-- Find monthly revenue for the year 2024.

SELECT MONTH(order_date) as month,
SUM(total_amount) as monthly_revenue
FROM sales
WHERE year(order_date)=2024
group by month(order_date)
order by month;


SELECT 
    MONTH(order_date) AS month,
    SUM(total_amount) AS monthly_revenue
FROM sales
WHERE YEAR(order_date) = 2024
GROUP BY MONTH(order_date)
ORDER BY month;

-- Which product generated the highest revenue overall?

SELECT product_name,sum(total_amount) as revenue from sales
GROUP BY product_name
ORDER BY  revenue DESC;


SELECT product_name, SUM(total_amount) AS revenue
FROM sales
GROUP BY product_name
ORDER BY revenue DESC
LIMIT 1;
-- Find orders where total_amount is greater than the average total_amount.
SELECT * FROM sales;
SELECT *
FROM sales
WHERE total_amount > (
    SELECT AVG(total_amount)
    FROM sales
);
-- Find the second highest revenue-generating city.
SELECT city,sum(total_amount) as revenue from sales
GROUP BY city
order by revenue desc limit 1,1;

