USE shirpur;

-- Showing the Dataset
SELECT * FROM products;

-- Finding the max value
SELECT MAX(discounted_price) FROM products;

SELECT MAX(discounted_price) FROM products
WHERE discounted_price=45900;

SELECT * FROM products
WHERE discounted_price=(SELECT MAX(discounted_price) FROM products);


-- Finding the min value
SELECT Min(discounted_price) FROM products;

SELECT * FROM products
WHERE discounted_price=49;

SELECT * from products
WHERE discounted_price = (SELECT Min(discounted_price) FROM products);

-- Finding the average value
SELECT AVG(discounted_price) FROM products;

SELECT * FROM products
WHERE discounted_price=1515 and rating>3;

-- Finding the average value of brand puma
SELECT avg(discounted_price) FROM products
WHERE brand_name='Puma';

-- Same command in one line
select avg(discounted_price),min(discounted_price),max(discounted_price) from products where brand_tag = 'puma';

-- Creating new columns of total revenue generated by each product
SELECT *,discounted_price*rating_count as Revenue FROM products;

-- Finding total revenue generated by all product
SELECT sum(discounted_price*rating_count) as total_revenue FROM products;

-- Finding total products
SELECT count(distinct product_name) as total_product from products;
select count(*) as 'Total Products' from products;

-- Finding number of products in Nike
select count(*) as 'Total Products' from products
WHERE brand_name='Nike';


-- Finding the name of categories nike serves
select distinct(product_tag) as 'Total Products' from products where brand_tag = 'nike';



-- Finding the number of categories nike serves
select count(distinct(product_tag)) as 'Total Products' from products where brand_tag = 'nike';



-- Finding the number of brands serves on myntra

select count(distinct(product_tag)) as 'Total Products' from products where brand_tag = 'myntra';

-- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------


-- 1. Finding the most expensive product on myntra
SELECT * from products 
ORDER BY discounted_price DESC LIMIT 1;

-- 2. Finding the least expensive product on myntra
SELECT * from products 
ORDER BY discounted_price ASC LIMIT 5;

-- 4. Top 5 products based on best rating | rating*rating count
SELECT product_name,rating,rating_count,round(rating*rating_count) as combi from products 
ORDER By combi desc limit 5;

-- 5. Finding the second most expensive product
SELECT * from products
ORDER BY discounted_price DESC LIMIT 1,1;

-- 6. Finding the second least expensive product
SELECT * from products
ORDER BY discounted_price ASC LIMIT 1,1;
-- 7. Finding the 10th most expensive product
SELECT * from products
ORDER BY discounted_price DESC LIMIT 9,1;
-- 8. Finding the worst rated product by nike
SELECT * from products
where brand_tag='Nike'
order by rating*rating_count asc limit 10;

select product_name , rating , rating_count, 
round(rating*rating_count) as 'comb_rating' from products
where brand_tag = 'nike'
order by comb_rating asc limit 5;
-- 9. Finding the worst rated product by nike & rating is not zero
select product_name , rating , rating_count, 
round(rating*rating_count) as 'comb_rating' from products
where brand_tag = 'nike' and rating !=0
order by comb_rating asc limit 5;

-- 10. Finding the top 10 best rated tshirt from nike or adidas | rating*rating count
SELECT product_name,brand_tag,product_tag, round(rating*rating_count) as combi from products
where brand_tag IN ('Nike', 'Adidas') and product_tag='tshirts'
order by combi desc limit 10;


-- 11. Worst rated 10 products based on the rating of 100 people atleast
SELECT * from products
WHERE rating_count>=100 
ORDER By rating asc LIMIT 10;


-- 12. 10 worst rated tshirt based on the rating of 100 people atleast
SELECT * from products
WHERE rating_count>=100 and product_tag='tshirts' 
ORDER By rating asc LIMIT 10;

-- 13. Sort the products in alphabetical descending order based on their product_name and show the last 10 of them

SELECT * from products
order by product_name desc limit 10;

-- 14. Finding the top 10 best rated tshirts from nike or adidas | rating*rating count
SELECT *,rating*rating_count as combi from products
where brand_tag IN ('Nike','adidas') and product_tag='tshirts'
ORDER BY combi desc LIMIT 10;

-- 15. Finding the list of tshirts from nike and adidas prices between 1000 and 1200 | Sort them based on ascending order of brand_name & price
select product_name , rating , rating_count, brand_tag, discounted_price from gfg.products
where brand_tag  in('nike','adidas') and product_tag = 'tshirts' and discounted_price between 1000 and 1200
order by brand_tag asc , discounted_price asc limit 10;

select product_name , rating , rating_count, brand_tag, discounted_price from gfg.products
where brand_tag  in('nike','adidas') and product_tag = 'tshirts' and discounted_price between 1000 and 2000
order by discounted_price asc, brand_tag asc;